name: ecr-docker-deployment
on: [push]
jobs:
  docker-cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        user: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, log, push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry  }}
          Repository: ecr-lambda-repo
          IMAGE_TAG: ${{ github.sha  }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push REGISTRY/$REPOSITORY:$IMAGE_TAG